export const FETCHING_USER_DATA = "FETCHING_USER_DATA";
export const FETCHING_USER_DATA_SUCCESS = "FETCHING_USER_DATA_SUCCESS";
export const FETCHING_USER_DATA_FAILED = "FETCHING_USER_DATA_FAILED";
export const FETCHING_ALL_PRODUCTS_DATA = "FETCHING_ALL_PRODUCTS_DATA";
export const FETCHING_ALL_PRODUCTS_DATA_SUCCESS =
  "FETCHING_ALL_PRODUCTS_DATA_SUCCESS";
export const FETCHING_ALL_PRODUCTS_DATA_FAILED =
  "FETCHING_ALL_PRODUCTS_DATA_FAILED";
export const FETCHING_ALL_CATEGORIES_DATA = "FETCHING_ALL_CATEGORIES_DATA";
export const FETCHING_ALL_CATEGORIES_DATA_SUCCESS =
  "FETCHING_ALL_CATEGORIES_DATA_SUCCESS";
export const FETCHING_ALL_CATEGORIES_DATA_FAILED =
  "FETCHING_ALL_CATEGORIESDATA_FAILED";
export const ADD_NEW_PRODUCT_DATA = "ADD_NEW_PRODUCTS_DATA";
export const ADD_NEW_PRODUCTS_DATA_SUCCESS = "ADD_NEW_PRODUCTS_DATA_SUCCESS";
export const ADD_NEW_PRODUCTS_DATA_FAILED = "ADD_NEW_PRODUCTS_DATA_FAILED";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART = "UPDATE_CART";
export const CREATE_NEW_INVOICE_DATA = "CREATE_NEW_INVOICE_DATA";
export const CREATE_NEW_INVOICE_DATA_SUCCESS =
  "CREATE_NEW_INVOICE_DATA_SUCCESS";
export const CREATE_NEW_INVOICE_DATA_FAILED = "CREATE_NEW_INVOICE_DATA_FAILED";
export const UPDATE_INVOICE_PRODUCTS_DATA = "UPDATE_INVOICE_PRODUCTS_DATA";
export const UPDATE_INVOICE_PRODUCTS_DATA_SUCCESS =
  "UPDATE_INVOICE_PRODUCTS_DATA_SUCCESS";
export const UPDATE_INVOICE_PRODUCTS_DATA_FAILED =
  "UPDATE_INVOICE_PRODUCTS_DATA_FAILED";
export const EMPTY_CART = "EMPTY_CART";
export const ADD_NEW_CATEGORY_DATA = "ADD_NEW_CATEGORY_DATA";
export const ADD_NEW_CATEGORY_DATA_SUCCESS = "ADD_NEW_CATEGORY_DATA_SUCCESS";
export const ADD_NEW_CATEGORY_DATA_FAILED = "ADD_NEW_CATEGORY_DATA_FAILED";
